import '@styles/globals.css'
import { type ReactNode } from 'react'

import { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import NextTopLoader from 'nextjs-toploader'

import ObservabilityProvider from '@providers/ObservabilityProvider'
import QueryProvider from '@providers/QueryProvider'
import SessionProvider from '@providers/SessionProvider'
import ThemeProvider from '@providers/ThemeProvider'
import ToastProvider from '@providers/ToastProvider'

const geistSans = Geist({
  subsets: ['latin'],
  variable: '--font-geist-sans'
})

const geistMono = Geist_Mono({
  subsets: ['latin'],
  variable: '--font-geist-mono'
})

export const metadata: Metadata = {
  description: 'Generated by upload next app',
  title: 'Create Next App'
}

export default function RootLayout({
  children
}: Readonly<{
  children: ReactNode
}>) {
  return (
    <SessionProvider>
      <html
        suppressHydrationWarning
        lang="en"
      >
        <body className={`${geistSans.variable} ${geistMono.variable}`}>
          <ObservabilityProvider>
            <QueryProvider>
              <NextTopLoader showSpinner={false} />
              <ThemeProvider themeProps={{ attribute: 'class', defaultTheme: 'dark' }}>
                <ToastProvider />
                {children}
              </ThemeProvider>
            </QueryProvider>
          </ObservabilityProvider>
        </body>
      </html>
    </SessionProvider>
  )
}
