import '@styles/globals.css'
import { type ReactNode } from 'react'

import { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'

import CustomThemeProvider from '@providers/CustomThemeProvider'
import ObservabilityProvider from '@providers/ObservabilityProvider'

const geistSans = Geist({
  subsets: ['latin'],
  variable: '--font-geist-sans'
})

const geistMono = Geist_Mono({
  subsets: ['latin'],
  variable: '--font-geist-mono'
})

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App'
}

export default function RootLayout({
  children
}: Readonly<{
  children: ReactNode
}>) {
  return (
    <html
      suppressHydrationWarning
      lang="en"
    >
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ObservabilityProvider>
          <CustomThemeProvider themeProps={{ attribute: 'class', defaultTheme: 'dark' }}>
            {children}
          </CustomThemeProvider>
        </ObservabilityProvider>
      </body>
    </html>
  )
}
